import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL ?? 'chrome', headless: true,
  args: ['--enable-webgl', '--ignore-gpu-blocklist'] })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(process.env.BASE_URL ?? 'http://127.0.0.1:5174')
  await page.locator('#floor-level').selectOption('upper')
  await page.locator('#third-person').click()
  await page.waitForFunction(() => document.querySelector('#status').textContent === 'Climbing upstairs', null, { timeout: 60000 })
  await page.waitForFunction(() => Number(document.querySelector('#scene').dataset.elevation) > 1.1, null, { timeout: 60000 })
  await page.locator('#pause').click()
  await page.screenshot({ path: '.artifacts/stair-climb.png', fullPage: true })
  await page.locator('#pause').click()
  await page.waitForFunction(() => document.querySelector('[data-destination="primary"]') !== null, null, { timeout: 90000 })
  await page.locator('#top').click()
  assert.equal(await page.locator('#play-fall').isDisabled(), true)
  assert.equal(await page.locator('[data-scenario="cart"]').isDisabled(), true)
  await page.screenshot({ path: '.artifacts/second-floor-plan.png', fullPage: true })
  await page.locator('[data-destination="primary"]').click()
  await page.waitForFunction(() => document.querySelector('#status').textContent.includes('Arrived'), null, { timeout: 60000 })
  await page.locator('#first-person').click()
  await page.screenshot({ path: '.artifacts/second-floor-interior.png', fullPage: true })
  await page.locator('#reset').click()
  assert.equal(await page.locator('#floor-level').inputValue(), 'upper')
  await page.locator('summary').click()
  const pending = page.waitForEvent('download')
  await page.locator('#export-house').click()
  const download = await pending
  assert.match(download.suggestedFilename(), /upper.*\.glb$/)
  const bytes = await readFile(await download.path())
  assert.equal(bytes.toString('ascii', 0, 4), 'glTF')
  assert.equal(bytes.readUInt32LE(4), 2)
  const jsonLength = bytes.readUInt32LE(12)
  const gltf = JSON.parse(bytes.toString('utf8', 20, 20 + jsonLength))
  assert.ok(gltf.nodes.some(n => n.name === 'bed-upper-primary'))
  await download.saveAs('.artifacts/tantau-upper-floor-reference.glb')
  await page.locator('#floor-level').selectOption('ground')
  await page.waitForFunction(() => document.querySelector('[data-destination="kitchen"]') !== null, null, { timeout: 90000 })
  await page.locator('#orbit').click()
  assert.equal(await page.locator('[data-destination="kitchen"]').count(), 1)
  await page.locator('#reset').click()
  await page.locator('[data-scenario="blocked"]').click()
  await page.locator('[data-destination="kitchen"]').click()
  await page.waitForFunction(() => document.querySelector('#status').textContent.includes('blocked'))
  await page.screenshot({ path: '.artifacts/house-materials.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('#floor-level').selectOption('upper')
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  assert.deepEqual(errors, [])
  console.log('Floor checks passed: selection, arrival, reset, interior view, GLB export, ground-floor scenario recovery, mobile layout, no page errors.')
} finally { await browser.close() }
