import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'

const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL ?? 'chrome', headless: true,
  args: ['--enable-webgl', '--ignore-gpu-blocklist'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
page.on('pageerror', error => errors.push(error.message))
const wait = fn => page.waitForFunction(fn, null, { timeout: 90000 })
try {
  await page.goto(process.env.BASE_URL ?? 'http://127.0.0.1:5174')
  await page.locator('#subject').selectOption('adult')
  await wait(() => document.querySelector('#speed').value === '1.3')
  await page.locator('#first-person').click()
  await page.locator('#floor-level').selectOption('upper')
  await wait(() => Number(document.querySelector('#scene').dataset.elevation) > 0.6)
  assert.equal(await page.locator('#scene').getAttribute('data-camera-mode'), 'first-person')
  await page.locator('#pause').click()
  await page.screenshot({ path: '.artifacts/stairs-first-person.png', fullPage: true })
  const paused = await page.locator('#scene').getAttribute('data-elevation')
  await page.locator('#third-person').click()
  assert.equal(await page.locator('#scene').getAttribute('data-elevation'), paused)
  await page.screenshot({ path: '.artifacts/stairs-third-person.png', fullPage: true })
  await page.locator('#pause').click()
  await wait(() => document.querySelector('#scene').dataset.floorLevel === 'upper')
  assert.equal(await page.locator('#scene').getAttribute('data-camera-mode'), 'third-person')
  await page.locator('#floor-level').selectOption('ground')
  await wait(() => document.querySelector('#scene').dataset.floorLevel === 'ground')
  // At the stair foot, turn toward the flight and enter using ordinary walking controls.
  await page.keyboard.down('ArrowLeft')
  await wait(() => -Math.sin(Number(document.querySelector('#scene').dataset.heading)) > 0.97)
  await page.keyboard.up('ArrowLeft')
  await page.keyboard.down('w')
  await wait(() => document.querySelector('#scene').dataset.stairControl === 'manual')
  await wait(() => Number(document.querySelector('#scene').dataset.elevation) > 0.5)
  await page.keyboard.up('w')
  await page.waitForTimeout(100)
  const stopped = await page.locator('#scene').getAttribute('data-elevation')
  await page.waitForTimeout(300)
  assert.equal(await page.locator('#scene').getAttribute('data-elevation'), stopped)
  await page.keyboard.press('v')
  await wait(() => document.querySelector('#first-person').getAttribute('aria-pressed') === 'true')
  await page.keyboard.down('w')
  await wait(() => document.querySelector('#scene').dataset.floorLevel === 'upper')
  await page.keyboard.up('w')
  await page.locator('#floor-level').selectOption('ground')
  await wait(() => document.querySelector('#scene').dataset.floorLevel === 'ground')
  await page.locator('#third-person').click()
  assert.equal(await page.locator('#fall-animation option').count(), 5)
  for (const kind of ['trip', 'patio', 'sideways', 'stairs', 'balcony']) {
    await page.locator('#fall-animation').selectOption(kind)
    await page.locator('#animation-speed').selectOption('0.5')
    await page.locator('#play-fall').click()
    await wait(() => Number(document.querySelector('#scene').dataset.fallProgress) > 0.45)
    await page.locator('#pause').click()
    await page.screenshot({ path: `.artifacts/fall-${kind}.png`, fullPage: true })
    const frozen = await page.locator('#scene').getAttribute('data-fall-progress')
    await page.waitForTimeout(150)
    assert.equal(await page.locator('#scene').getAttribute('data-fall-progress'), frozen)
    await page.locator('#animation-speed').selectOption('1')
    await page.locator('#pause').click()
    await wait(() => document.querySelector('#status').textContent.includes('down'))
    await page.locator('#play-fall').click()
    await page.locator('#reset').click()
    await wait(() => document.querySelector('#status').textContent === 'Ready to explore')
  }
  await page.locator('#subject').selectOption('grandma-figurine')
  await wait(() => document.querySelector('#motion-note').textContent.includes('Controlling'))
  await page.locator('#fall-animation').selectOption('sideways')
  await page.locator('#play-fall').click()
  await wait(() => document.querySelector('#status').textContent.includes('down'))
  await page.setViewportSize({ width: 390, height: 844 })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  assert.deepEqual(errors, [])
  console.log('Passed: first/third-person stair traversal, camera changes, keyboard stair entry/release/resume, five falls, pause/replay/reset, figurine, mobile, no page errors.')
} catch (error) {
  await page.screenshot({ path: '.artifacts/situations-failure.png', fullPage: true })
  console.error('Page errors:', errors)
  throw error
} finally { await browser.close() }
